      USE CONSTANTS, only : UNDEF, RADIUS, DERA, DAIR, SRCE_DIRECT, LPDLIB
      USE CONSTANTS, only : SRCE_DIRECT, LPDLIB, SRCE_IMP_POST, SRCE_IMP_PRE
      USE CONSTANTS, only : TPIINV

      USE W3GDATMD, only : IGRID, NSEAL, NSPEC, NX, NY, NK
      USE W3GDATMD, only : GTYPE, UNGTYPE, SMCTYPE, RSTYPE, FILEXT
      USE W3GDATMD, only : MAPSF, MAPFS, MAPSTA, IOBP, CTHG0S
      USE W3GDATMD, only : FLCTH, FSREFRACTION, FLCK, FSFREQSHIFT, FLAGLL, FLDRY
      USE W3GDATMD, only : FSTOTALIMP, FLCX, FLCY, FLSOU, FLAGST
      USE W3GDATMD, only : SIG, CLATS, TRNX, TRNY
      USE W3GDATMD, only : DTMAX, DTCFLI, DTH, DMIN

      USE W3WDATMD, only : UST, IWDATA, TIME, TLEV, TICE, TIC1, VA, ASF, RHOAIR
      USE W3WDATMD, only : USTDIR, ICE, ICEH, ICEF, ICEDMAX, BERG, FPIS

      USE W3ADATMD, only : FLIWND, FLCOLD,  IAPPRO, IDLAST
      USE W3ADATMD, only : IADATA, IPASS, ITIME, CFLXYMAX, CFLTHMAX, CFLKMAX, DTDYN
      USE W3ADATMD, only : CG, DW, CX, CY, DCDX, DCDY, DCXDX, DCXDY, DCYDX, DCYDY
      USE W3ADATMD, only : AS, TAUOX, TAUOY, TAUWIX, TAUWIY, TAUWNX, TAUWNY, DDDX, DDDY
      USE W3ADATMD, only : ALPHA, WN, U10, U10D, TAUA, TAUADIR, FCUT, WHITECAP, BEDFORMS
      USE W3ADATMD, only : TAUBBL, TAUICE, PHIBBL, TAUOCX, TAUOCY, WNMEAN, PHIAW, PHIOC
      USE W3ADATMD, only : TWS, PHICE, CHARN

      USE W3IDATMD, only : IIDATA
      USE W3IDATMD, only : INFLAGS1, FLLEV, FLCUR, FLWIND, FLICE, FLTAUA, FLRHOA
      USE W3IDATMD, only : FLIC1, FLIC2, FLIC3, FLIC4, FLIC5
      USE W3IDATMD, only : TLN, TC0, TCN, TW0, TWN, TIN, TU0, TUN, TI1, TGN, TG0, GA0, GAN
      USE W3IDATMD, only : GD0, GDN, TDN, TRN

      USE W3ODATMD, only : FLOUT, FLOGRD, FLOGR2, FLBPI, NOGE
      USE W3ODATMD, only : NDS, NOGE, NAPLOG, NAPOUT, NDSO, NDSE, NDST, NAPROC, NAPERR, SCREEN
      USE W3ODATMD, only : IAPROC, IOUTP, NOTYPE, NAPBPT
      USE W3ODATMD, only : TOFRST, TONEXT, TBPIN, TBPI0, TOLAST, DTOUT, NAPFLD, NAPPNT

      USE W3GDATMD, only : W3SETG
      USE W3ODATMD, only : W3SETO
      USE W3ADATMD, only : W3SETA
      USE W3WDATMD, only : W3SETW
      USE W3IDATMD, only : W3SETI
      USE W3UPDTMD, only : W3DZXY, W3UWND, W3UINI, W3UTAU, W3URHO, W3UBPT, W3UICE
      USE W3UPDTMD, only : W3ULEV, W3UCUR, W3UIC1, W3UTRN
      USE W3SRCEMD, only : W3SRCE
      USE W3TRIAMD, only : UG_GRADIENTS
      USE W3IOGOMD, only : W3IOGO, W3OUTG
      USE W3IOPOMD, only : W3IOPO, W3IOPE
      USE W3IOTRMD, only : W3IOTR
      USE W3IORSMD, only : W3IORS
      USE W3IOBCMD, only : W3IOBC
      USE W3IOSFMD, only : W3IOSF, W3CPRT
      USE W3SERVMD, only : EXTCDE, WWTIME
      USE W3TIMEMD, only : DSEC21, TICK21, STME21
#ifdef W3_MPI
      USE W3ODATMD, only : NRQGO, NRQGO2, IRQGO, IRQGO2, NRQPO, NRQPO2, IRQPO1, IRQPO2
      USE W3ODATMD, only : NRQRS, IRQRS, IRQPO1, NRQBP, IRQBP1, IRQBP2, NRQBP2
      USE W3ADATMD, only : NRQSG1, IRQSG1, NRQSG1, MPI_COMM_WAVE
#endif
#ifdef W3_REF1
      USE W3GDATMD, only : RLGTYPE, SX, SY, CLGTYPE, HPFAC, HQFAC, REFLC, REFLD
#endif
#ifdef W3_BT4
      USE W3GDATMD, only : SED_D50, SED_PSIC
#endif
#ifdef W3_PR1
      USE W3PRO1MD,  only : W3MAP1, W3XYP1, W3KTP1
      USE W3PROFSMD, only : W3XYPUG
#endif
#ifdef W3_PR2
      USE W3PRO2MD,  only : W3XYP2, W3MAP2, W3KTP2
      USE W3PROFSMD, only : W3XYPUG
#endif
#ifdef W3_PR3
      USE W3PRO3MD,  only : W3MAPT, W3XYP3, W3CFLXY, W3MAP3, W3KTP3
      USE W3PROFSMD, only : W3XYPUG, W3CFLUG
#endif
#ifdef W3_SMC
      USE W3GDATMD, only : ANGARC, ARCTC, NBAC, NBGL, NGLO, NCel, ICLBAC, SPCBAC
      USE W3ADATMD, only : DHDX, DHDY, DHLMT
      USE W3GDATMD, only : NTH
      USE W3PSMCMD, only : SMCDHXY, SMCDCXY, W3SCATSMC, W3GATHSMC, W3PSMC, W3KRTN
      USE W3SERVMD, only : W3ACTURN
#endif
#ifdef W3_PDLIB
      USE W3PARALL       , only : PDLIB_NSEAL, PDLIB_NSEALM, LSLOC
      USE W3WDATMD       , only : VAOLD, VSTOT, VDTOT, SHAVETOT
      USE W3GDATMD       , only : FSSOURCE, FSTOTALEXP
      USE W3GDATMD       , only : IOBP_LOC, IOBPD_LOC, IOBPA_LOC, IOBDP_LOC
      USE yowNodepool    , only : npa, iplg, np
      USE PDLIB_W3PROFSMD, only : APPLY_BOUNDARY_CONDITION_VA
      USE PDLIB_W3PROFSMD, only : PDLIB_W3XYPUG, PDLIB_W3XYPUG_BLOCK_IMPLICIT, PDLIB_W3XYPUG_BLOCK_EXPLICIT
      USE PDLIB_W3PROFSMD, only : ALL_VA_INTEGRAL_PRINT, ALL_VAOLD_INTEGRAL_PRINT, ALL_FIELD_INTEGRAL_PRINT
      USE PDLIB_W3PROFSMD, ONLY: ASPAR_JAC, ASPAR_DIAG_ALL, B_JAC
      USE PDLIB_FIELD_VEC, only : DO_OUTPUT_EXCHANGES
#endif
#ifdef W3_IC3
      USE W3GDATMD, only : IC3PARS
      USE W3SIC3MD, only : CALLEDIC3TABLE, IC3TABLE_CHENG, W3IC3WNCG_V1, W3IC3WNCG_CHENG
      USE W3IDATMD, only : ICEP1, ICEP2, ICEP3, ICEP4
#endif
#ifdef W3_IS2
      USE W3WDATMD, only : TIC5
      USE W3IDATMD, only : TI5
      USE W3UPDTMD, only : W3UIC5
#endif
#ifdef W3_UOST
      USE W3UOSTMD, ONLY: UOST_SETGRID
#endif
      USE W3PARALL, ONLY : INIT_GET_ISEA
#ifdef W3_MEMCHECK
      USE MallocInfo_m
#endif
#ifdef W3_SETUP
      USE W3WAVSET, only : WAVE_SETUP_COMPUTATION
#endif

#ifdef W3_OASIS
      USE W3WDATMD, ONLY: TIME00, TIMEEND
      USE W3OACPMD, ONLY: ID_OASIS_TIME, CPLT0
#endif
#ifdef W3_OASOCM
      USE W3OGCMMD, ONLY: SND_FIELDS_TO_OCEAN
#endif
#ifdef W3_OASACM
      USE W3AGCMMD, ONLY: SND_FIELDS_TO_ATMOS
#endif
#ifdef W3_OASICM
      USE W3IGCMMD, ONLY: SND_FIELDS_TO_ICE
#endif

#ifdef W3_TIMINGS
    USE W3PARALL, only : PRINT_MY_TIME
#endif
#if defined(W3_UWMNCOUT) || defined(W3_CESMCOUPLED)
      ! flags for restart and history writes
      USE WAV_SHR_MOD , only : RSTWR, HISTWR
      USE W3IOGONCDMD , ONLY : W3IOGONCD
#endif
!
      IMPLICIT NONE
!
#ifdef W3_MPI
      INCLUDE "mpif.h"
#endif
