#!/bin/bash

set -x

cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_core.res.tile1.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_core.res.tile1.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_core.res.tile2.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_core.res.tile2.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_core.res.tile3.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_core.res.tile3.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_core.res.tile4.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_core.res.tile4.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_core.res.tile5.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_core.res.tile5.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_core.res.tile6.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_core.res.tile6.nc
 
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_srf_wnd.res.tile1.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_srf_wnd.res.tile1.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_srf_wnd.res.tile2.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_srf_wnd.res.tile2.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_srf_wnd.res.tile3.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_srf_wnd.res.tile3.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_srf_wnd.res.tile4.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_srf_wnd.res.tile4.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_srf_wnd.res.tile5.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_srf_wnd.res.tile5.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_srf_wnd.res.tile6.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_srf_wnd.res.tile6.nc
 
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_tracer.res.tile1.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_tracer.res.tile1.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_tracer.res.tile2.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_tracer.res.tile2.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_tracer.res.tile3.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_tracer.res.tile3.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_tracer.res.tile4.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_tracer.res.tile4.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_tracer.res.tile5.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_tracer.res.tile5.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/fv_tracer.res.tile6.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/fv_tracer.res.tile6.nc
 
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/phy_data.tile1.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/phy_data.tile1.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/phy_data.tile2.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/phy_data.tile2.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/phy_data.tile3.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/phy_data.tile3.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/phy_data.tile4.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/phy_data.tile4.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/phy_data.tile5.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/phy_data.tile5.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/phy_data.tile6.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/phy_data.tile6.nc
 
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/sfc_data.tile1.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/sfc_data.tile1.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/sfc_data.tile2.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/sfc_data.tile2.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/sfc_data.tile3.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/sfc_data.tile3.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/sfc_data.tile4.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/sfc_data.tile4.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/sfc_data.tile5.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/sfc_data.tile5.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/sfc_data.tile6.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/sfc_data.tile6.nc

cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/iced.2016-10-05-00000.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/iced.2016-10-05-00000.nc

cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/MOM.res.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/MOM.res.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/MOM.res_1.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/MOM.res_1.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/MOM.res_2.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/MOM.res_2.nc
cmp cpld_fv3_384_mom6_cice_restart_cmeps_atm_flux/RESTART/MOM.res_3.nc cpld_fv3_384_mom6_cice_2d_cmeps_atm_flux/RESTART/MOM.res_3.nc

